# I use the base Debian image because it matches the same base image
# the Cloudbees Jenkins image
FROM debian:jessie
MAINTAINER Rodrigo Villamil Perez

# Volume for postgess database
VOLUME ["/var/lib/postgresql/data/pgdata"]

CMD ["echo", "Postgres: Volume data container ready!"]
